# fly.toml app configuration file generated for restless-firefly-2892 on 2023-06-21T03:05:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restless-firefly-2892"
primary_region = "nrt"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  APP_URL = "https://restless-firefly-2892.fly.dev"
  APP_NAME = "Laravel"
  APP_DEBUG = false
  DB_CONNECTION = "pgsql"
  DB_HOST = "db.xgddcfviprmrpzivhoim.supabase.co"
  DB_PORT = 5432
  DB_DATABASE = "postgres"
  DB_USERNAME = "postgres"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
